[loggers]
keys=root,httpx,httpcore

[handlers]
keys=console

[formatters]
keys=default

[logger_root]
level=DEBUG
handlers=console

[logger_httpx]
level=WARNING
handlers=
qualname=httpx
propagate=1

[logger_httpcore]
level=WARNING
handlers=
qualname=httpcore
propagate=1

[handler_console]
class=StreamHandler
level=NOTSET
formatter=default
args=(sys.stderr,)

[formatter_default]
format=%(asctime)s | %(levelname)-8s | %(name)s | %(message)s
datefmt=%Y-%m-%d %H:%M:%S
