# plugins.yaml lists all plugins available to the agent.  Agent reads this file
# on start and loads all listed plugins by calling `loadOmegaClawPlugin`
# function. Please see `pluginapi.metta` and `pluginapi.py` to understand which
# API is available to plugins.
#
# Plugin can be implemented as a MeTTa module, a single Python file or
# a Python module. The plugin record has the following fields:
# - name - required, each plugin should have an unique name
# - loader - required, `metta` or `python` the runtime which should be used to
# load the plugin
# - location - optional field, should be specified if plugin is a single Python
# file; can include `{REPO}` placeholder to designate the root folder of the
# OmegaClaw source repository.

- name: irc
  loader: python
  location: "{REPO}/channels"

#- name: telegram
  #loader: python
  #location: "{REPO}/channels"

#- name: slack
  #loader: python
  #location: "{REPO}/channels"

- name: mattermost
  loader: python
  location: "{REPO}/channels"

  ## FIXME: rename mock to mockchannel
#- name: mockchannel
  #loader: python
  #location: "{REPO}/channels"

- name: openaiapi
  loader: python
  location: "{REPO}/providers"

#- name: asione
  #loader: python
  #location: "{REPO}/providers"

#- name: openrouter
  #loader: python
  #location: "{REPO}/providers"

#- name: openai
  #loader: python
  #location: "{REPO}/providers"

#- name: mockprovider
  #loader: python
  #location: "{REPO}/providers"
