name: Sonar Analysis Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:

jobs:
  sonar:
    uses: singnet/security-workflows/.github/workflows/sonar.yml@master
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      OPENSEARCH_URL: ${{ secrets.OPENSEARCH_URL }}
      OPENSEARCH_USER: ${{ secrets.OPENSEARCH_USER }}
      OPENSEARCH_PASS: ${{ secrets.OPENSEARCH_PASS }}
